$ SET COMMAND GCC.CLD /TABLES=SYS$COMMON:[SYSLIB]DCLTABLES.EXE -
                      /OUTPUT=SYS$COMMON:[SYSLIB]DCLTABLES.EXE
$ INSTALL REPLACE SYS$SHARE:DCLTABLES.EXE
$ LIBRARY/HELP SYS$HELP:HELPLIB.HLB GCC.HLP/REPLACE
$ @gcc_startup
