(defun tkb-right-justify ()
  (interactive)
  (let ((p (make-marker))
	(d 0))
    (set-marker p (point))
    (end-of-line)
    (setq d (- 80 (current-column)))
    (goto-char p)
    (if (> d 0)
	(insert-char ? d))
    (goto-char p)
    (setq p nil)))
